
server {
    listen 8080;
    server_name localhost;

    root /var/www/html;
    index index.html;

    error_page 404 /404.html;

    location /images/ {
        root /var/www/images;
        autoindex on;
    }

    location /upload/ {
        root /var/www/upload;
        client_max_body_size 10M;
    }
}
